theme: jekyll-theme-cayman
title: "Building Research Software Communities: How to increase engagement in your community"
description: A workshop in the SORSE series - 17th/18th March 2021, 09:00-11:00 UTC
