theme: jekyll-theme-cayman
title: "Building Research Software Communities: How to increase engagement in your community"
description: "A workshop in the <a href=\"https://sorse.github.io\">SORSE series</a> - 17th/18th March 2021, 09:00-11:00 UTC"
github:
  is_project_page: false