theme: jekyll-theme-cayman
title: Building Research Software Communities: How to increase engagement in your community
description: A workshop in the <a href="https://sorse.github.io/" target="_blank" rel="noopener noreferrer">SORSE series</a> of online research software events<br/>17th/18th March 2021, 09:00-11:00 UTC
